# Generated by Django 5.2.3 on 2025-06-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('date_created', models.DateField(verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('expected_result', models.CharField(max_length=200)),
                ('result', models.CharField(choices=[('notrun', 'Not Run'), ('pass', 'Pass'), ('fail', 'Fail')], default='notrun', max_length=10)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase')),
            ],
        ),
    ]
